config/routes.rb
SampleDemoProject1::Application.routes.draw do
  devise_for :users
  resources :holds

  resources :boys

  resources :resources

  resources :users

  resources :fasts
  resources :dm_dnets
  resources :dnt_formats
  resources :dnt_platforms
  resources :banks

    resources :clients
    resources :multirow_texts  
    resources :sponsors
    resources :calculations
    resources :cities
    resources :banks  

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is_system_admin?
      can :manage, [Bank, UserProfile, CiCompany, UserInvitation]
    end
    if user.is_bank_admin?
      can :manage, [Bank, UserProfile, UserInvitation]
      can :read, CiCompany
    end
    if user.is_banking_professional?
      can :read, UserProfile
      can :read, Bank
    end
    if user.is_cic_admin?
      can :manage, [UserProfile, CiCompany, UserInvitation]
    end
    if user.construction_inspector?
      can :read, UserProfile
      can :read, CiCompany
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/assembly.rb
class Assembly < ActiveRecord::Base
end

app/models/bank.rb
class Bank < ActiveRecord::Base
  has_many :projects
  has_many :cics, through: :projects
  has_many :employees, as: :employable
  has_many :users, through: :employees
  has_one :address, as: :addressable
  accepts_nested_attributes_for :address
  validates :bank_name , presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/boy.rb
class Boy < ActiveRecord::Base
end

app/models/city.rb
class City <MultirowText

end

app/models/client.rb
class Client <ActiveRecord::Base

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	 # validates :name, presence : true
	 # validates :exclusion: { in: %w(www us ca jp), message: "%{value} is reserved." }
	 # has_many :orders

end

app/models/dm_dnet.rb
class DmDnet < ActiveRecord::Base
  include Segmentable

  # belongs_to :segment
  belongs_to :currency_cdlk
  
  validates :currency_cdlk_id, allow_blank: true, numericality: { only_integer: true}
  validates :min_order_qty,:change_address_qty,:hotline_qty,:total_file_qty,
            length: { maximum: 8},
            numericality: { only_integer: true},
            allow_nil: true
  validates :gender_male_pct,:gender_female_pct,:age_average,:age_from,:age_to,
            length: { maximum: 3},
            numericality: { only_integer: true},
            allow_nil: true
  validates :min_order_amt,:total_file_amt,
            allow_blank: true,
            numericality: true,
            format: {with: /(^\d{0,8}(\.\d{0,2})?$)/ }
  validates :average_unit_of_sale,
            allow_blank: true,
            numericality: true,
            format: {with: /(^\d{0,3}(\.\d{0,2})?$)/ }
  validate :currency_cdlk_exists

  before_save :validate_percentage

  def currency_cdlk_exists
    return true if (currency_cdlk_id.nil? || DmDnet.currency_cdlk_drop_down.empty?)
    _valid_values = DmDnet.currency_cdlk_drop_down.map(&:last)
    errors.add(:base, 'Currency must exist') unless _valid_values.include?(self.currency_cdlk_id)
  end

  # Use to drive form view Ad Unit drop down selection
  def self.currency_cdlk_drop_down
    CurrencyCdlk.all.map{|d| [d.description, d.id] }
  end

  def validate_percentage
    self.errors.add(:base, ' sum of male % and female% must be less than or equal to 100') unless [gender_male_pct.to_i,gender_female_pct.to_i].sum <= 100
  end
end

app/models/dnt_format.rb
class DntFormat < ActiveRecord::Base
  include Segmentable
  # belongs_to :segment

  validates :image_accepted_flag,:flash_accepted_flag,:rich_media_accepted_flag,:video_accepted_flag,:preroll_accepted_flag,
            :midroll_accepted_flag,:postroll_accepted_flag,:overlay_accepted_flag,:iab_vast_certified_accepted_flag,
            :iab_vpaid_certified_accepted_flag,
            length: { maximum: 1 }
end

app/models/hold.rb
class Hold < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
	  # belongs_to :customer
end

app/models/part.rb
class Part < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/physician.rb
class Physician < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  BANK_ADMIN = 'bank_admin'
  BANKING_PROFESSIONAL = 'banking_professional'
  CONSTRUCTION_INSPECTION_COMPANY_ADMIN = 'cic_admin'
  CONSTRUCTION_INSPECTOR = 'construction_inspector'
  SYSTEM_ADMIN = 'system_admin'

  has_one :user_role
  has_many :user_invitations
  has_many :users, through: :user_role
  
  scope :system_admin, -> {find_by_alias(SYSTEM_ADMIN)}
  scope :bank_admin, -> {find_by_alias(BANK_ADMIN)}
  scope :banking_professional, -> {find_by_alias(BANKING_PROFESSIONAL)}
  scope :cic_admin, -> {find_by_alias(CONSTRUCTION_INSPECTION_COMPANY_ADMIN)}
  scope :construction_inspector, -> {find_by_alias(CONSTRUCTION_INSPECTOR)}
end

app/models/sponsor.rb
class Sponsor <MultirowText

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :user_role
  has_many :role, through: :user_role
  has_one :user_profile
  has_many :user_invitations, as: :joinable
  has_one :employee

  has_many :cic_assigned_projects, class_name: "Project", foreign_key: "raised_by_id"
  has_many :raised_bank_projects, class_name: "Project", foreign_key: "assigned_to_id"

  has_many :assigned_inspection_requests, class_name: "ProjectInspectionRequest", foreign_key: "raised_by_id"
  has_many :raised_inspection_requests, class_name: "ProjectInspectionRequest", foreign_key: "assigned_to_id"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def is_system_admin?
    have_role?(Role::SYSTEM_ADMIN)
  end

  def is_bank_admin?
    have_role?(Role::BANK_ADMIN)
  end

  def is_banking_professional?
    have_role?(Role::BANKING_PROFESSIONAL)
  end

  def is_cic_admin?
    have_role?(Role::CONSTRUCTION_INSPECTION_COMPANY_ADMIN)
  end

  def construction_inspector?
    have_role?(Role::CONSTRUCTION_INSPECTOR)
  end

  def have_role?(role_type)
    role.pluck(:alias).include? role_type if role
  end
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cus_id %><br>
    <%= f.number_field :cus_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cus</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.cus_id %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Cus:</strong>
  <%= @resource.cus_id %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/shared/_char_count.html.erb
<div id="<%= seg %>_count">
    <span class='count'>
      <%= obj.send(seg).present? ? (size - obj.send(seg).length) : size %>
    </span>
    <span class='character'>
      <%= obj.send(seg).present? ? 'Characters Left' : 'Characters Max' %>
    </span>
</div>

app/views/shared/_display_multiple_values.html.erb
<table id="<%= display_id %>" class="<%=  specific_class %> fixed_table col-xs-12" >
  <tbody>
  <% unless multi_table.blank? %>
      <% if (field_id == 'profile_specialities_input') %>
          <% multi_table.reverse.each do |obj| %>
              <%- if obj.code_lookup.present?  %>
                  <tr id="<%= field_id %>_<%= obj.code_lookup_id %>">
                    <td class="word_wrap col-xs-6"><%= obj.code_lookup.description %></td>
                    <td id="<%= field_id %>_delete_<%= obj.code_lookup_id %>"><%= link_to '','#', class: 'glyphicon glyphicon-remove', title: 'Delete' unless current_party.published? %></td>
                    <script>
                        deleteRecord("<%= field_id %>","<%= obj.code_lookup_id %>","<%= container %>","<%= display_id %>","<%= obj.code_lookup_id %>");
                    </script>
                  </tr>
              <% end %>
          <% end %>
      <% elsif(field_id == 'ooh_closing_time_row_header' || field_id == 'ooh_closing_time_column_header' || field_id == 'ooh_closing_time_row_header_list' || field_id == 'ooh_closing_time_column_header_list') %>
          <% multi_table.reverse.each do |obj| %>
              <%- if obj.send(field).present?  %>
                  <tr id="<%= field_id %>_<%= obj.id %>">
                    <td class="word_wrap col-xs-6"><%= obj.send(field) %></td>
                    <td id="<%= field_id %>_delete_<%= obj.id %>"><%= link_to '','#', class: 'glyphicon glyphicon-remove', title: 'Delete' unless current_party.published? %></td>
                    <script>
                        deleteRecord("<%= field_id %>","<%= obj.send(field) %>","<%= container %>","<%= display_id %>","<%= obj.id %>");
                    </script>
                  </tr>
              <% end %>
          <% end %>
      <% else %>
          <% multi_table.reverse.each do |obj| %>
              <tr id="<%= field_id %>_<%= obj.id %>">
                <td class="col-xs-10" title="<%= obj.text %>"><%= truncate(obj.text, length: 20) %></td>
                <td id="<%= field_id %>_delete_<%= obj.id %>"><%= link_to '','#', class: 'glyphicon glyphicon-remove', title: 'Delete' unless current_party.published? %></td>
                <script>
                    deleteRecord("<%= field_id %>","<%= obj.text %>","<%= container  %>","<%= display_id %>","<%= obj.id %>");
                 </script>
              </tr>
          <% end %>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/shared/_facility_search_field.html.erb
<div class='clear_with_height_20'></div>
<%= f.input search_field.to_sym, label: input_field.upcase+' Search',
            input_html: { id: segment+'_search_field',class: 'form-control col-xs-6', type: 'no_submit' }  %>
<%= link_to 'Search', '#', class: 'btn btn-primary', id: 'search_'+segment  %>
<div class='clear_with_height_20'></div>
<div id='search_result_<%= segment %>'></div>
<%= f.input input_field.to_sym, label: input_field.upcase+' Name',
            input_html: {class: 'form-control col-xs-10 pull-left', readonly: true,
                         value: (obj.characteristic_id.nil? || obj.id.nil?) ? '' : select_obj(Dma,obj.characteristic_id).name} %>
<%= f.hidden_field :characteristic_id %>
<div class='clear_with_height_20'></div>
<script>
    // to populate input value for search param
    $('#search_<%= segment %>').on('click', function(e) {
        e.preventDefault();
        $.ajax({
            data:'facility_search='+ $('#<%= segment %>_search_field').val(),
            type:'get',
            url: '/<%= segment.pluralize %>'
        })
    });
</script>

app/views/shared/_flash_mesg.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_paid_assets_user_detail_for_segment.html.erb
<div class='btn-group pull-right user_details' id='<%= segment %>_btn'>
  <span>
    <% if obj.present? && obj.updated_at.present? %>
      <i class='icon-user'></i> <%= obj.segment.user.username  %>
        <span> | <%= obj.updated_at.strftime('%m/%d/%Y') %></span>
    <% end %>
  </span>
  <span>
    <% unless current_party.published? %>
        <%= f.submit 'RESET', class: 'custom btn btn-default', id: 'reset_'+ segment %>
        <%= f.submit 'APPLY TO DIGITAL MATCH', class: 'custom btn btn-default', id: 'apply_to_digital_match_'+ segment %>
        <%= f.submit 'SAVE' , class: 'custom btn btn-default', id: 'save_'+ segment  %>
    <% end %>
  </span>
</div>

app/views/shared/_paid_assets_user_detail_without_save_reset.html.erb
<div class='btn-group pull-right user_details' id='<%= segment %>_btn'>
  <span>
    <% if obj.present? && obj.updated_at.present? %>
      <i class='icon-user'></i> <%= obj.segment.user.username  %>
        <span> | <%= obj.updated_at.strftime('%m/%d/%Y') %></span>
    <% end %>
  </span>
  <span>
    <% unless current_party.published? %>
        <%= f.submit 'APPLY TO DIGITAL MATCH', class: 'custom btn btn-default', id: 'apply_to_digital_match_'+ segment %>
    <% end %>
  </span>
</div>

app/views/shared/_party_user_details.html.erb
<div class='btn-group pull-right title_user_details'>
    <span>
      <% if party.user.present? && party.updated_at.present? && display_user  %>
          <i class='icon-user'></i> <%= party.reload.user.username  %> |
          <span>
            <%= party.reload.updated_at.strftime('%m/%d/%Y') %>
          </span>
      <% end %>
      <% unless party.published? %>
          <%= f.submit 'RESET', class: 'custom btn btn-default', id: 'reset_'+ segment %>
          <%= f.submit 'SAVE' , class: 'custom btn btn-default', id: 'save_'+ segment  %>
      <% end %>
    </span>
</div>

app/views/shared/_party_user_details_no_parent.html.erb
<div class='btn-group pull-right user_details'>
    <span>
      <% if party.user.present? && display_user  %>
          <i class='icon-user'></i> <%= party.user.username  %> |
          <span>
            <%= party.updated_at.strftime('%m/%d/%Y') if party.updated_at.present? %>
          </span>
      <% end %>
      <% unless party.published? %>
          <%= f.submit 'RESET', class: 'custom btn btn-default', id: 'reset_'+ segment %>
          <%= f.submit 'SAVE' , class: 'custom btn btn-default', id: 'save_'+ segment  %>
      <% end %>
    </span>
</div>

app/views/shared/_search_result_for_facility.html.erb
<table id='<%= segment %>_table' class='<%= specific_css_class %> width-85 table table-bordered'>
  <% unless objs.each_hit_with_result.first.nil? %>
      <% objs.each_hit_with_result do |hit,facility| %>
          <tr>
            <td><%= facility.name %></td>
            <td class='pull-right'><%= link_to 'select','#', id: 'select_'+segment, onclick: "fill_#{segment}_name('#{facility.name}','#{facility.id}'); return false;" %></td>
          </tr>
      <% end %>
  <% else %>
      <tr>
        <td>No Records Found</td>
      </tr>
      </table>
  <% end  unless objs.blank? %>
</table>
<div class='clear_with_height_20'></div>

app/views/shared/_user_detail_for_party.html.erb
<div class='btn-group pull-right user_details' id='<%= segment %>_btn'>
  <span>
    <% if obj.present? && show_details(obj,fields) && obj.updated_at.present? && obj.party.user.present? %>
      <i class='icon-user'></i> <%= obj.party.user.username  %>
        <span> | <%= obj.updated_at.strftime("%m/%d/%Y") %></span>
    <% end %>
  </span>
  <span>
    <% unless current_party.published? %>
      <%= f.submit 'RESET', class: 'custom btn btn-default', id: 'reset_'+ segment %>
        <%= f.submit 'SAVE' , class: 'custom btn btn-default', id: 'save_'+ segment  %>
    <% end %>
  </span>
</div>

app/views/shared/_user_detail_for_segment.html.erb
<div class='btn-group pull-right user_details' id='<%= segment %>_btn'>
  <span>
    <% if obj.present? && obj.updated_at.present? && obj.segment.user.present? %>
      <i class='icon-user'></i> <%= obj.segment.user.username  %>
      <span> | <%= obj.updated_at.strftime("%m/%d/%Y") %></span>
    <% end %>
  </span>
  <span>
    <% unless current_party.published? %>
      <%= f.submit 'RESET', class: 'custom btn btn-default', id: 'reset_'+ segment %>
      <%= f.submit 'SAVE' , class: 'custom btn btn-default', id: 'save_'+ segment  %>
    <% end %>
  </span>
</div>

app/views/shared/_user_details_only_save.html.erb
<div class='btn-group pull-right user_details'>
    <span>
      <% if obj.present?  %>
          <i class='icon-user'></i> <%= obj.segment.user.username %> |
          <span><%= obj.updated_at.strftime('%m/%d/%Y') %></span>
      <% end %>
      <%= f.submit 'SAVE', class: 'custom btn btn-default' unless current_party.published? %>
    </span>
</div>

app/views/shared/addressing_delivery/_dm_delivery_part1.html.erb
<div class='col-md-4' id='from_days'>
  <%= f.input :from_days, label: 'From Days', input_html: {class: 'form-control col-xs-3'} %>
</div>
<div class='col-md-4' id='to_days'>
  <%= f.input :to_days, label: 'To Days', input_html: {class: 'form-control col-xs-3'} %>
</div>
<div class='col-md-4' id='workdays'>
  <%= f.input :workdays, as: :boolean, label: 'Workdays' %>
</div>
<div class='clear_with_height'></div>

<div class='col-md-12' id='delivery_other'>
  <%= f.input :delivery_other, as: :text, label: 'Delivery Other',
              input_html: {class: 'form-control col-xs-10 text_area_resizing', rows:3} %>
</div>

<div class='clear_with_height'></div>
<div class='col-md-5' id='delivery_24_hour'>
  <%= f.input :delivery_24_hour, as: :boolean, label: '24 hr Delivery' %>
</div>
<div class='col-md-4' id='cost_24_hour'>
  <%= f.input :cost_24_hour, label: '24 hr Cost', input_html: {class: 'form-control col-xs-4'} %>
</div>

<div class='clear_with_height'></div>
<div class='col-md-5' id='delivery_48_hour'>
  <%= f.input :delivery_48_hour, as: :boolean, label: '48 hr Delivery' %>
</div>
<div class='col-md-4' id='cost_48_hour'>
  <%= f.input :cost_48_hour, label: '48 hr Cost', input_html: {class: 'form-control col-xs-4'} %>
</div>

app/views/shared/addressing_delivery/_dm_delivery_part2.html.erb
<div class='col-md-5' id='ncoa'>
  <%= f.input :ncoa, as: :boolean, label: 'NCOA' %>
</div>
<div class='col-md-4'>
  <%= f.input :cass_certified, as: :boolean, label: 'CASS Certified' %>
</div>
<div class='clear_with_height'></div>
<div class='col-md-4' id='delivery_guarantee_pct'>
  <%= f.input :delivery_guarantee_pct, label: 'Delivery Guarantee Percent', input_html: {class: 'form-control col-xs-3'} %>
</div>
<div class='clear_with_height'></div>
<div class='col-md-12' id='delivery_guarantee_desc'>
  <%= f.input :delivery_guarantee_desc, as: :text, label: 'Delivery Guarantee Other',
              input_html: {class: 'form-control col-xs-10 text_area_resizing', rows:3} %>
</div>

app/views/shared/dashboard/_parties.html.erb
<% unless  @party.nil? %>

  <div class="row" style="background-color:#EEEEEE;padding:0px;padding-top:3px;">

    <div class="col-md-8">
        <span class="d-label">Type: </span><%= @party.media_type.name %>
    </div>

    <div class="col-md-4 text-right">
        <span class="d-label">Status: </span>
        <span class="label <%= @party.state_label %>">
            <%= @party.human_friendly_state %>
        </span>
        <span class="glyphicon glyphicon-step-forward"></span>
        <span class="label label-primary">
             <%= link_to @party.transition[1] , transition_state_path(@party.transition[0], hide_popup: true),
             :style => "color:white", data: {confirm: 'Are you sure?'} %>
        </span>
         &nbsp;&nbsp;&nbsp;&nbsp;
        <a href="#"  title="Print View"><span class="glyphicon glyphicon-print"></span></a>&nbsp;
    </div>  

  </div>

  <div class="row" style="background-color:#EEEEEE;padding:0px;padding-bottom:3px;">
    <div class="col-md-12">
        <span class="d-label">MID: </span><%= @party.mid %>
        <span class="d-label">Name: </span> <%= @party.name %>
    </div>

  </div>

<% end %>

app/views/shared/dashboard/_party.html.erb

<% unless  @party.nil? %>
<div class="row pad5">

  <div class="col-md-8">
      <span class="d-label">Mid: </span><%= @party.mid %>
      <span class="d-label">Media Name: </span> <%= @party.name %>
      <span class="d-label">Media Type: </span><%= @party.media_type.name %>
  </div>

  <div class="col-md-4 text-right">
       &nbsp;&nbsp;&nbsp;&nbsp;
      <a href="/parties"  title="Close Datacard"><span class="glyphicon glyphicon-folder-close"></span></a>
     </div>      
  </div>

<% end %>

app/views/shared/linkings/_address_header.html.erb
<tr class='grey_color'>
  <td></td>
  <td colspan='2'>Company Name</td>
  <td colspan='2'>Address</td>
</tr>

app/views/shared/linkings/_address_person_header.html.erb
<tr class='grey_color'>
  <td width='65%'><%= @person.present? ? 'Person Details' : 'Address Details' %></td>
  <td width='10%' class='align-center'>Media</td>
  <td width='10%' class='align-center'>Segment</td>
  <td width='15%' class='align-center'>Actions</td>
  <td></td>
</tr>

app/views/shared/linkings/_display_address.html.erb
<% unless address_objs.blank? %>
    <% address_objs.each do |address| %>
        <tr id="<%= seg %>_<%= address.id %>">
          <td colspan="2"><%= h address.xref.party.name %></td>
          <td colspan="3" class='word_wrap'><%= display_address(address.xref) %></td>
          <td colspan="2">
            <%= link_to '', address_linking_path(address.id, segment_detail_id: sub_seg), method: :delete,
                        data: { confirm: 'Are you sure?' } , remote: true, class: 'glyphicon glyphicon-remove padding-15' unless current_party.published? %>
          </td>
        </tr>
    <% end %>
<% else %>
    <tr>
      <td colspan='4'>No records found</td>
    </tr>
<% end %>

app/views/shared/linkings/_display_emails_linking_search_result.html.erb
<% unless email_objs.blank? %>
    <% unless email_objs.each_hit_with_result.first.nil? %>
        <%= render 'shared/linkings/email_shared_header' %>
        <% selected_objs_ids = selected_objs ? selected_objs.collect{|object| object.xref_id } : nil %>
        <% email_objs.each_hit_with_result do |hit,email_obj| %>
            <tr id='tr_<%= email_obj.id %>'>
              <td align="center">
                <% selected = (selected_objs_ids ? selected_objs_ids.include?(email_obj.id) : false) %>
                <%= check_box_tag email_obj.party.name, email_obj.id, selected ,disabled: selected, title: (selected ? 'Already Added' : '') %>
              </td>
              <td>
                <%= h email_obj.party.name %>
              </td>
              <td><%= email_obj.email_type_cdlk.description %></td>
              <td colspan="2" class='word_wrap'><%= email_obj.email %></td>
            </tr>
        <% end %>
    <% else %>
        <%= render 'shared/linkings/email_shared_header' %>
        <tr><td colspan='4'>No records found</td></tr>
    <% end %>
<% end %>

app/views/shared/linkings/_display_emails_type.html.erb
<% unless email_objs.blank? %>
    <% email_objs.each do |email_obj| %>
        <tr id="<%= seg %>_<%= email_obj.id %>">
          <td><%= h email_obj.xref.party.name %></td>
          <td><%= email_obj.xref.email_type_cdlk.description %></td>
          <td colspan="3" class='word_wrap'><%= email_obj.xref.email %></td>
          <td colspan="1">
            <%= link_to '', email_linking_path(email_obj, segment_detail_id: sub_seg), method: :delete,
                        data: { confirm: 'Are you sure?' } , remote: true, class: 'glyphicon glyphicon-remove padding-15 mrgn_top_3' unless current_party.published? %>
          </td>
        </tr>
    <% end %>
<% else %>
    <tr>
      <td colspan='4'>No records found</td>
    </tr>
<% end %>

app/views/shared/linkings/_display_personals.html.erb
<% unless person_obj.blank? %>
    <% person_obj.each do |personal| %>
        <tr id="general_personal_<%= personal.id %>">
          <td>
            <%= h personal.xref.party.name %>
          </td>
          <td colspan="3" class='word_wrap'><%= display_person_detail(personal.xref) %> </td>
          <td>
            <%= link_to '', person_linking_path(personal.id, segment_detail_id: sub_seg), method: :delete,
                            data: { confirm: 'Are you sure?' } , remote: true, class: 'glyphicon glyphicon-remove padding-15 mrgn_top_3' unless current_party.published? %>
          </td>
        </tr>
    <% end %>
<% else %>
    <tr>
      <td colspan='4'>No records found</td>
    </tr>
<% end %>

app/views/shared/linkings/_display_search_result_address.html.erb
<% unless address_objs.blank? %>
    <% unless address_objs.each_hit_with_result.first.nil? %>
        <%= render 'shared/linkings/address_header' %>
        <% selected_objs_ids = selected_objs ? selected_objs.collect{|object| object.xref_id } : nil %>
        <% address_objs.each_hit_with_result do |hit,address| %>
            <tr id='tr_<%= address.id %>'>
              <td>
                <% selected = (selected_objs_ids ? selected_objs_ids.include?(address.id) : false) %>
                <%= check_box_tag address.party.name, address.id, selected ,disabled: selected, title: (selected ? 'Already Added' : '') %>
              </td>
              <td colspan='2'>
                <%= h address.party.name %>
              </td>
              <td colspan='2' class='word_wrap'><%= display_address(address) %></td>
            </tr>
        <% end %>
    <% else %>
        <%= render 'shared/linkings/address_header' %>
        <tr>
          <td colspan='4'>No records found</td>
        </tr>
    <% end %>
<% end %>

app/views/shared/linkings/_person_linking_header.html.erb
<tr class='grey_color'>
  <td width='30%'>Company Name</td>
  <td colspan="3">Personal Details</td>
  <td></td>
</tr>